---
- name: codey | Ensuring group settings
  group:
    name: codey
    state: '{{codey_state}}'
    gid: 1666396

- name: codey | Ensuring user settings
  ignore_errors: yes
  user:
    name: codey
    uid: 1666396
    state: '{{codey_state}}'
    group: users
    groups: '{{codey_groups}}'
    comment: 'Codey Oxley'
    shell: /usr/bin/zsh

- name: codey | Installing public key
  authorized_key:
    user: codey
    state: '{{codey_state}}'
    key: "{{ lookup('file', item) }}"
  with_items:
    - rsa.pub
